# Generated by Django 5.2.13 on 2026-04-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_rename_message_sid"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="follow_up_trigger_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_sid",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="FollowUpSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("interval_value", models.PositiveIntegerField()),
                (
                    "interval_unit",
                    models.CharField(
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        default="days",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_up_schedules",
                        to="messaging.messagetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "follow_up_schedules",
                "ordering": ["interval_value", "name"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="follow_up_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to="messaging.followupschedule",
            ),
        ),
    ]
