# Generated by Django 5.2.13 on 2026-04-21 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_rename_message_sid"),
    ]

    operations = []
