# Generated by Django 5.2.13 on 2026-04-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_message_sid'),
        ('messaging', '0003_message_follow_up_trigger_at_and_more'),
    ]

    operations = [
    ]
