# Generated by Django 5.0.6 on 2026-04-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_merge_0004_initial_0004_merge_20260421_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='follow_up_trigger_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FollowUpSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interval_value', models.PositiveIntegerField()),
                ('interval_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='days', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_schedules', to='messaging.messagetemplate')),
            ],
            options={
                'db_table': 'follow_up_schedules',
                'ordering': ['interval_value', 'id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='follow_up_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.followupschedule'),
        ),
    ]
