# Generated by Django 6.0.1 on 2026-01-11 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('condition', models.CharField(choices=[('heart_failure', 'Heart Failure'), ('copd', 'COPD'), ('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('pneumonia', 'Pneumonia'), ('other', 'Other')], max_length=50)),
                ('secondary_conditions', models.JSONField(blank=True, default=list)),
                ('discharge_date', models.DateField()),
                ('discharge_notes', models.TextField(blank=True)),
                ('medications', models.JSONField(default=list)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('current_risk_level', models.CharField(choices=[('green', 'Low Risk'), ('yellow', 'Moderate Risk'), ('red', 'High Risk')], default='green', max_length=10)),
                ('preferred_check_in_time', models.TimeField(default='09:00')),
                ('monitoring_active', models.BooleanField(default=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='providers.provider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-current_risk_level', '-created_at'],
            },
        ),
    ]
