# Generated by Django 6.0.4 on 2026-04-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('phone_number_raw', models.CharField(max_length=30)),
                ('phone_number_e164', models.CharField(db_index=True, max_length=20, unique=True)),
                ('condition', models.CharField(max_length=255)),
                ('secondary_conditions', models.TextField(blank=True, default='')),
                ('medications', models.TextField(blank=True, default='')),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True, default='')),
                ('external_reference', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('preferred_check_in_time', models.TimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('sms_opt_in', models.BooleanField(default=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_source', models.CharField(blank=True, default='', max_length=100)),
                ('monitoring_active', models.BooleanField(default=True)),
                ('follow_up_end_date', models.DateField(blank=True, null=True)),
                ('current_risk_level', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('opted_out', 'Opted Out'), ('unreachable', 'Unreachable')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
