# Generated by Django 6.0.4 on 2026-04-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='providers.provider'),
        ),
    ]
