# Generated by Django 5.2.13 on 2026-04-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="assigned_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="providers.provider",
            ),
        ),
    ]
