# Generated by Django 5.2.13 on 2026-04-21 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
        ("providers", "0001_initial"),
    ]

    operations = []
