# Generated by Django 5.2.13 on 2026-04-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options'),
        ('patients', '0003_alter_patient_options'),
    ]

    operations = [
    ]
