# Generated by Django 5.0.6 on 2026-04-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_initial'),
        ('patients', '0004_merge_20260421_0629'),
    ]

    operations = [
    ]
