# Generated by Django 6.0.1 on 2026-01-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='patients.patient')),
            ],
            options={
                'db_table': 'daily_checkins',
                'ordering': ['-scheduled_date', '-scheduled_time'],
                'unique_together': {('patient', 'scheduled_date')},
            },
        ),
        migrations.CreateModel(
            name='CheckInResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('response_value', models.CharField(max_length=255)),
                ('response_score', models.IntegerField(default=0)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checkins.dailycheckin')),
            ],
            options={
                'db_table': 'checkin_responses',
                'ordering': ['responded_at'],
            },
        ),
    ]
