# Generated by Django 6.0.4 on 2026-04-22 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('response_value', models.CharField(max_length=255)),
                ('raw_response_text', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'checkin_responses',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('reminded', 'Reminded'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('question_keys', models.JSONField(default=list)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('missed_time', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_checkins',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
