# Generated by Django 6.0.4 on 2026-04-22 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
        ('messaging', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinresponse',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='checkinresponse',
            name='source_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.message'),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='checkinresponse',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checkins.dailycheckin'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycheckin',
            unique_together={('patient', 'scheduled_date')},
        ),
    ]
