# Generated by Django 5.0.6 on 2026-04-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_add_question_keys'),
        ('checkins', '0002_initial'),
    ]

    operations = [
    ]
